# Generated by Django 4.0.3 on 2022-05-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_faces_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='face_rec',
            field=models.BooleanField(default=False),
        ),
    ]
