# Generated by Django 4.0.3 on 2022-05-27 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_face_rec'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='face_rec',
            new_name='face',
        ),
    ]
