# Generated by Django 4.0.3 on 2022-05-29 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.CharField(default='0', max_length=10),
            preserve_default=False,
        ),
    ]
